### ISSUE TITLE
Memorize the language used in the previous submission

### ISSUE THREAD

**Issue by JacobLinCool** [Normal-OJ/new-front-end#100]
Can we add a feature to remember the language used in the previous submission? It would save time and effort.

One possible solution could be to use client-side local storage to store the language selected in the previous submission. This would allow the browser to remember the user's preferred language and automatically preselect it in the language dropdown menu for future submissions.

Thanks!

**Comment by uier** [comment]
Sure, this is a pain point that needs to be addressed. I will create a PR soon.
