### ISSUE TITLE
選擇語言的選單移至 code 之上

### ISSUE THREAD

**Issue by uier** [Normal-OJ/new-front-end#105]
By @ra890927

**Comment by uier** [comment]
@ra890927 說明一下這個 issue 的上下文？我猜是因為貼上 code 之後就可以直接選語言按送出，但這兩個 UI 卻需要滾到下面才能使用？

**Comment by uier** [comment]
不對欸，我在 Chrome & Firefox 都是貼完 code 之後會自動到 code editor 的 bottom，所以不會有這個問題

**Comment by ra890927** [comment]
這個怎麼感覺跟我們那天討論的有點不一樣 @Bogay ，那時候不是說要把 submit 那些用成跟 leetcode 那樣的嗎?

**Comment by Bogay** [comment]
> 那時候不是說要把 submit 那些用成跟 leetcode 那樣的嗎?

精確一點來說結論是兩個都可以，如果沒有其他意見的話就看動手的人怎麼做。

**Comment by ra890927** [comment]
那如果是要做 submit 那塊放到最上面的話，那貼程式的時候 code editor 不能移到 bottom，不然還要移到頂部，反而不好用

**Comment by uier** [comment]
> 那如果是要做 submit 那塊放到最上面的話，那貼程式的時候 code editor 不能移到 bottom，不然還要移到頂部，反而不好用
> 
> 

所以原本的介面有什麼問題？我從會議紀錄看不出來

**Comment by uier** [comment]
> 我平常是用 brave 有時候遇過複製完 code editor 沒有在底部的狀況

「有時候」聽起來像是 browser 的問題 XD？

**Comment by ra890927** [comment]
這樣看來短期內應該不用改這部分了
