### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by Bogay** [Normal-OJ/new-front-end#18]
- [x] Submission query @ `src/pages/course/[name]/submissions.vue`
- [x] Error of post card @ `src/components/PostCard.vue`

**Comment by uier** [comment]
我發現我用的[自動 import 套件](https://github.com/antfu/unplugin-vue-components)，我沒有 configure 好 components.d.ts 的設定，所以 types error 遠比兩個 items 多很多 XD
