### ISSUE TITLE
Using HOC or other patterns to handle loading/error UI

### ISSUE THREAD

**Issue by uier** [Normal-OJ/new-front-end#34]
We have a few components are using this kind of logic to handle loading state & error state

```vue
<div v-if="error" class="alert alert-error shadow-lg">
  <div>
    <i-uil-times-circle />
    <span>Oops! Something went wrong when loading announcements.</span>
  </div>
</div>
<skeleton-table v-else-if="isLoading" :col="3" :row="5" />
<table v-else class="table w-full">
```

Would be better to apply a HOC (Higher Order Component), for example

```vue
<HOC :loading-ui="<component>" :error-ui="<component>" :data-ui="<component>" />
```

**Comment by Bogay** [comment]
How about using slot instead of attribute?

**Comment by laporchen** [comment]
> How about using slot instead of attribute?

Error is a different component. I think using attribute might be a better solution.

**Comment by uier** [comment]
Both ways are good in my opinion.

error component & loading component can be passed as either props or slot.

I think only data ui I'll probably put it in slot
