### ISSUE TITLE
@Misawai 將協助我們加入繁體中文的對照字典

### ISSUE THREAD

**Issue by uier** [Normal-OJ/new-front-end#49]
Before 1/31 ends: 學生看得到的畫面
- [x] /index (home)
- [x] /courses
- [x] /course/[name]/announcements/index
- [x] /course/[name]/announcements/[id]/index
- [x] /course/[name]/homeworks/index
- [x] /course/[name]/problems
- [x] /course/[name]/submissions
- [x] /course/[name]/problem/[id]/index
- [x] /course/[name]/problem/[id]/submit
- [x] /course/[name]/problem/[id]/stats
- [x] /course/[name]/submission/[id]
- [x] /about
- [x] /profile
- [x] /settings

**Comment by Misawai** [comment]
course/[name]/members 這個學生應該看不到?

**Comment by uier** [comment]
@Misawai 經確認 `/course/[name]/homeworks/[id]/stats` 是學生不會看到的，稍後會移除

是否就剩下最後一個 `/course/[name]/problem/[id]/stats` 要進行翻譯，有安排時間進行了嗎？

**Comment by Misawai** [comment]
@uier 其實已經翻譯完了但還沒提 PR。目前 PR 已提 ( #60、#61、#62、#63、#64）。

**Comment by Misawai** [comment]
> @Misawai 經確認 `/course/[name]/homeworks/[id]/stats` 是學生不會看到的，稍後會移除
> 
> 是否就剩下最後一個 `/course/[name]/problem/[id]/stats` 要進行翻譯，有安排時間進行了嗎？

@uier 其實已經翻譯完了但還沒提 PR。目前 PR 已提 ( #60、#61、#62、#63、#64）。

**Comment by uier** [comment]
@Misawai 請問此 issue 還有未完成的部分嗎？

**Comment by Misawai** [comment]
都翻完了，目前我的帳號沒有看到尚未翻譯到的部分
