### ISSUE TITLE
Sample test data got blocked by COPY button

### ISSUE THREAD

**Issue by uier** [Normal-OJ/new-front-end#80]
Expect to reserve the room for COPY button to avoid blocking the content

![image](https://user-images.githubusercontent.com/16915098/224907031-7d2c1c0f-4770-4448-93aa-6f18e0d0ff58.png)

![image](https://user-images.githubusercontent.com/16915098/224907092-35c077b6-9621-42e0-b4d1-3c11386bc641.png)

**Comment by JacobLinCool** [comment]
I believe using the `group` and `group-hover` approach to display the button is a great solution to this problem.

By implementing this approach, the button will only appear when the user hovers over the code block, avoiding any potential blocking issues. This way, users can still easily copy the content by selecting the text directly, and will discover the button when they hover over the area, making the functionality easily accessible.

**Comment by JacobLinCool** [comment]
I would love to contribute to this feature, please let me know how I can help.
