### ISSUE TITLE
Change Tab Size for Code Preview

### ISSUE THREAD

**Issue by JacobLinCool** [Normal-OJ/new-front-end#98]
Dear NOJ Maintainers,

I noticed that the current tab size for the code preview is set to `inherit`, which inherits a `1.5em` value. However, I find that this causes lines with tabs to be misaligned and difficult to read.

To improve the readability, I propose changing the tab size for the code preview to 4 spaces. This will make it easier to read.

I would like to submit a pull request to implement the change when I am available.

Please let me know if there are any concerns or questions regarding this proposed change.

Thank you for your time.

<img width="329" alt="misaligned" src="https://user-images.githubusercontent.com/28478594/230389657-8ddc8dcd-d363-4c26-a294-9eff53ebcce0.png">

**Comment by uier** [comment]
I strongly agree with your proposal. No question for me 😃 

Thank you!
